// Generated by scripts/generate-circuit-sprites.py -- do not edit.
// Circuit's pixel art (ADR 0030), drawn by that script.
#pragma once

#include <cstdint>

namespace drehklang::games::circuit_art {

// 8-bit indexed pixels, row-major; index 0 is transparent.
struct Sprite {
  uint16_t width;
  uint16_t height;
  const uint8_t *pixels;
};

// Colours a track paints without sprites: the sky in hard bands
// from the top down to the horizon, and the road's alternating
// light/dark bands.
struct Palette {
  uint16_t slots[32];  // RGB565 for each sprite index
  uint16_t sky[6];
  uint16_t grass[2];
  uint16_t road[2];
  uint16_t rumble[2];
  uint16_t lane;
};

constexpr int kPaletteSlots = 32;
constexpr uint8_t kBodySlot = 2;
constexpr uint8_t kStripeSlot = 3;
constexpr int kLiveryCount = 4;
// Body and stripe colours of the computer cars, RGB565.
extern const uint16_t kLiveries[kLiveryCount][2];

extern const Sprite kCarStraight;
extern const Sprite kCarLeft;
extern const Sprite kCarRight;
extern const Sprite kPalm;
extern const Sprite kCactus;
extern const Sprite kRock;
extern const Sprite kLamp;
extern const Sprite kSign;
extern const Sprite kTower;
extern const Sprite kBanner;
extern const Sprite kExplosion0;
extern const Sprite kExplosion1;
extern const Sprite kExplosion2;

constexpr int kTrackCount = 3;
extern const Palette kPalettes[kTrackCount];
extern const Sprite kBackdrops[kTrackCount];

// 5x7 glyphs in an 8x8 cell, one byte per row, bit 4 leftmost.
// nullptr for a character the font does not have.
const uint8_t *glyph(char c);

}  // namespace drehklang::games::circuit_art
